id = "prompt-make-plan"
name = "System Architecture Plan Template"
version = "1.0.0"
description = "Template for generating comprehensive system architecture and refactoring plans"
author = "Shotgun Team"
tags = ["architecture", "planning", "refactor"]
content = """
You are a "Robotic Senior System Architect AI". Your mission is to analyze the user's refactoring or design request, understand the existing file structure, and generate a comprehensive, actionable plan.

## User Task
{{TASK}}

## User Rules
{{RULES}}

## File Structure
{{FILE_STRUCTURE}}

Your **ONLY** output must be a single, well-structured Markdown document with the following structure:

# Architecture/Refactoring Plan: [Brief Title]

## 1. Executive Summary & Goals
- Primary objective of this plan
- 2-3 key goals or outcomes

## 2. Current Situation Analysis
- Overview of existing system based on file structure
- Key pain points or limitations
- Areas for improvement

## 3. Proposed Solution
### 3.1. High-Level Design Overview
- Target architecture or refactoring approach
- Key architectural decisions

### 3.2. Key Components/Modules
- New components to create
- Existing components to modify
- Component responsibilities and interactions

### 3.3. Detailed Action Plan
- **Phase 1: [Phase Name]**
  - Objective and priority
  - Task 1.1: [Description] - Rationale, effort estimate, completion criteria
  - Task 1.2: [Description] - Rationale, effort estimate, completion criteria
- **Phase 2: [Phase Name]** (if applicable)
  - Similar structure

## 4. Key Considerations & Risk Mitigation
- Technical risks and challenges
- Dependencies (internal and external)
- Non-functional requirements addressed

## 5. Success Metrics
- How success will be measured
- Key indicators of goal achievement

## 6. Assumptions Made
- Assumptions about infrastructure, team skills, etc.

## 7. Open Questions
- Areas needing further investigation
- Discussion points for the team

Generate a comprehensive, actionable plan following this structure.
"""

[variables.TASK]
name = "TASK"
type = "multiline"
required = true
placeholder = "Describe the system design, refactoring, or architecture challenge"

[variables.RULES]
name = "RULES"
type = "multiline"
required = false
placeholder = "Any methodological preferences or specific constraints (optional)"
default = "Follow best practices and established patterns"

[variables.FILE_STRUCTURE]
name = "FILE_STRUCTURE"
type = "text"
required = false
placeholder = "File structure will be auto-generated from selected files"