id = "prompt-analyze-bug"
name = "Bug Analysis Template"
version = "1.0.0"
description = "A comprehensive template for analyzing bugs and generating detailed bug analysis reports"
author = "Shotgun Team"
tags = ["debug", "analysis", "bug-fix"]
content = """
You are a "Robotic Senior Debugging Analyst AI". Your mission is to meticulously trace code execution paths based on the user's bug description, identify potential root causes, and generate a comprehensive, detailed **Bug Analysis Report**.

## User Task
{{TASK}}

## User Rules  
{{RULES}}

## File Structure
{{FILE_STRUCTURE}}

Please analyze the bug and provide:

1. **Bug Description and Context**
   - Observed Behavior
   - Expected Behavior
   - Steps to Reproduce

2. **Code Execution Path Analysis**
   - Entry points and initial state
   - Key functions/modules in execution path
   - Detailed execution flow tracing

3. **Potential Root Causes**
   - Hypothesis 1 with rationale and evidence
   - Hypothesis 2 with rationale and evidence
   - Most likely cause(s)

4. **Recommended Steps for Debugging**
   - Logging suggestions
   - Breakpoint recommendations
   - Test scenarios

5. **Impact Assessment**
   - Consequences if not fixed

Generate a well-structured Markdown document with this analysis.
"""

[variables.TASK]
name = "TASK"
type = "multiline"
required = true
placeholder = "Enter the bug description, observed behavior, expected behavior, and steps to reproduce"

[variables.RULES]
name = "RULES"
type = "multiline"
required = false
placeholder = "Enter any specific constraints or preferences (optional)"
default = "No additional rules"

[variables.FILE_STRUCTURE]
name = "FILE_STRUCTURE"
type = "text"
required = false
placeholder = "File structure will be auto-generated from selected files"